apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: {{ .Values.labels.app }}
spec:
  accessModes:
    - ReadWriteOnce {{ .Values.accessModes }}
  resources:
    requests:
      storage: 10Gi {{ .Values.resources.requests.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql {{ include " .Values.fullname" }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    matchLabels:
      app: wordpress {{ .Values.labels.app }}
      tier: mysql    {{ .Values.labels.tier }}
  strategy:
    type: Recreate  {{ .Values.strategy.type }}
  
    spec:
      containers:
      - image: mysql:5.6 {{ .Values.image.repositories }}
        name: mysql {{ .Values.image.name }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

