apiVersion: v1
kind: Service
metadata:
  name: wordpress {{ .Values.service.name }}
  labels:
    app: wordpress {{ .Values.labels.app }}
spec:
  ports:
    - port: 80 {{ .Values.service.port }}
  selector:
    app: wordpress {{ .Values.selector.app }}
    tier: frontend {{ .Values.selector.tier }}
  type: NodePort {{ .Values.service.type }}
