apiVersion: v1
kind: Service
metadata:
  name: wordpress {{ .Values.service.name }}
  labels:
    app: wordpress {{ .Values.labels.app }}
spec:
  ports:
    - port: 80 {{ .Values.service.port }}
  selector:
    app: wordpress {{ .Values.selector.app }}
    tier: frontend {{ .Values.selector.tier }}
  type: NodePort {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress {{ include "wordpress.fullname" . }}
  labels:
    app: wordpress {{ .Values.labels.app }}
spec:
  selector:
    matchLabels:
      app: wordpress {{ .Values.selector.app }}
      tier: frontend {{ .Values.selector.tier }}
  strategy:
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        app: wordpress {{ .Values.template.app }}
        tier: frontend {{ .Values.template.tier}}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name}}
      containers:
      - image: wordpress:4.8-apache {{ .Values.image.repository }}
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret {{ .Values.secret.name}}
              key: password
        ports:
        - containerPort: 80
          name: wordpress
  
